name: Build and deploy Node.js app to Azure Web App

env:
  AZURE_WEBAPP_NAME: SleeperTiers  # set this to the name of your Azure Web App
  NODE_VERSION: '14.x'              # set this to the Node.js version to use

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      # Optional: Add step to run tests here

      - name: Build for production
        run: npm run build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            ./build
            # Include other necessary files/directories for deployment

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Add other necessary configuration options for Node.js deployment
