name: Build and deploy Node.js app to Azure Web App

env:
  AZURE_WEBAPP_NAME: SleeperTiers  # set this to the name of your Azure Web App
  NODE_VERSION: '14.x'              # set this to the Node.js version to use

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      # Optional: Add step to run tests here

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            # Specify the directory where your Node.js application resides
            .
            # Exclude any unnecessary files or directories, e.g., node_modules

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
